{"name": "test_valid_email_wrong_password", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'AUTHENTICATION' == 'MY ACCOUNT'\n  - MY ACCOUNT\n  + AUTHENTICATION", "trace": "@pytest.mark.failed\n    def test_valid_email_wrong_password():  # -> Error\n        '''\n        Check valid email and wrong password\n        :return: Error message: \"Authentication failed.\"\n        failed\n        '''\n        startTest()\n        username = \"tamar.samara@gmail.com\"\n        password = \"ttttt\"\n>       email_try_except(username, password)\n\ntestLogin1.py:84: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nusername = 'tamar.samara@gmail.com', password = 'ttttt'\n\n    def email_try_except(username, password):\n        try:\n            login(id=username, param=\"email\")\n            time.sleep(1)\n            login(id=password, param=\"passwd\")\n            time.sleep(1)\n        except Exception as e:\n            print(\"error in code: {}\".format(e))\n    \n        finally:\n            element1 = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID,\n                                                                                       \"SubmitLogin\")))\n            element1.click()\n            # ErrorPage = \"\"\n            # ErrorPage = driver.find_element(By.TAG_NAME, \"h1\").text\n            # if ErrorPage ==\n            elem_page_heading = driver.find_element(By.CLASS_NAME, \"page-heading\")\n            print(f'page-headinggggggggggg {elem_page_heading.text}')\n            elemerror = driver.find_element(By.TAG_NAME, \"ol\")\n            print(f'elemerror.text {elemerror.text}')\n            logging.info(f'Successful Login')\n            logging.warning(f'Error message: {elemerror.text}')\n>           assert elem_page_heading.text == \"MY ACCOUNT\"\nE           AssertionError: assert 'AUTHENTICATION' == 'MY ACCOUNT'\nE             - MY ACCOUNT\nE             + AUTHENTICATION\n\ntestLogin1.py:54: AssertionError"}, "description": "\n    Check valid email and wrong password\n    :return: Error message: \"Authentication failed.\"\n    failed\n    ", "attachments": [{"name": "log", "source": "8a47fd64-7a4a-474b-8cc2-1fada1d4a61a-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "6436b1b3-f95d-4d54-abd5-b67c1ca2904b-attachment.txt", "type": "text/plain"}], "start": 1660433320465, "stop": 1660433340620, "uuid": "2699047c-6714-4b81-932c-223b18a0bad2", "historyId": "75c55ea2b222207b2bbcaadb68912569", "testCaseId": "9df949c7c71675637924ead7249dc58c", "fullName": "testLogin1#test_valid_email_wrong_password", "labels": [{"name": "tag", "value": "failed"}, {"name": "suite", "value": "testLogin1"}, {"name": "host", "value": "tamar1"}, {"name": "thread", "value": "24240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testLogin1"}]}