{"name": "test_wrong_email_wrong_password", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'AUTHENTICATION' == 'MY ACCOUNT'\n  - MY ACCOUNT\n  + AUTHENTICATION", "trace": "@pytest.mark.failed\n    def test_wrong_email_wrong_password():  # -> Error\n        '''\n        Wrong email check and wrong password\n        :return: Error message: \"Invalid email address.\"\n        failed\n        '''\n        startTest()\n        username = \"tamarsamara\"\n        password = \"ttttt\"\n>       email_try_except(username, password)\n\ntestLogin1.py:71: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nusername = 'tamarsamara', password = 'ttttt'\n\n    def email_try_except(username, password):\n        try:\n            login(id=username, param=\"email\")\n            time.sleep(1)\n            login(id=password, param=\"passwd\")\n            time.sleep(1)\n        except Exception as e:\n            print(\"error in code: {}\".format(e))\n    \n        finally:\n            element1 = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID,\n                                                                                       \"SubmitLogin\")))\n            element1.click()\n            # ErrorPage = \"\"\n            # ErrorPage = driver.find_element(By.TAG_NAME, \"h1\").text\n            # if ErrorPage ==\n            elem_page_heading = driver.find_element(By.CLASS_NAME, \"page-heading\")\n            print(f'page-headinggggggggggg {elem_page_heading.text}')\n            elemerror = driver.find_element(By.TAG_NAME, \"ol\")\n            print(f'elemerror.text {elemerror.text}')\n            logging.info(f'Successful Login')\n            logging.warning(f'Error message: {elemerror.text}')\n>           assert elem_page_heading.text == \"MY ACCOUNT\"\nE           AssertionError: assert 'AUTHENTICATION' == 'MY ACCOUNT'\nE             - MY ACCOUNT\nE             + AUTHENTICATION\n\ntestLogin1.py:54: AssertionError"}, "description": "\n    Wrong email check and wrong password\n    :return: Error message: \"Invalid email address.\"\n    failed\n    ", "attachments": [{"name": "log", "source": "3f0f8893-b274-4c2b-948d-c480d42c6d27-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "fac9dacf-fa4b-4b54-83a5-689a444de0a3-attachment.txt", "type": "text/plain"}], "start": 1660433296719, "stop": 1660433318802, "uuid": "0bdc8413-69d3-4140-93ec-6d71df388254", "historyId": "2b859dfb2b8db20929208d753e61c13f", "testCaseId": "471049969dd8e892dbe50c0b2091067d", "fullName": "testLogin1#test_wrong_email_wrong_password", "labels": [{"name": "tag", "value": "failed"}, {"name": "suite", "value": "testLogin1"}, {"name": "host", "value": "tamar1"}, {"name": "thread", "value": "24240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testLogin1"}]}